### ISSUE TITLE
Добавление комментариев к ДТП

### ISSUE THREAD

**Issue by ustnv** [dtpstat/dtp-project#5]
Добавить возможность оставлять комментарии под любым ДТП. Это нужно, если кто-то захочет добавить ссылку на видео или еще что-то про ДТП.

Поля: имя, комментарий и капча. 
Пока без модерирования, пусть комментарии мгновенно публикуются.

- [x] https://github.com/dtpstat/dtp-map/issues/80
- [x] https://github.com/dtpstat/dtp-map/issues/86
- [x] https://github.com/dtpstat/dtp-map/issues/82
- [x] https://github.com/dtpstat/dtp-map/issues/90

**Comment by sergous** [comment]
В ходе реализации внесли такие поправки:

1. Капчи нет, есть полноценная авторизация через Auth0. Пока есть по почте или логину Google, можно добавить другие соцсети.
2. Модерацию сделали быстрым способом - публикация после проставления флага прямо в базе данных
